/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ttt.h"


void
ttt_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	char *currentboard_1_arg;
	int  *result_2;
	play_args  play_1_arg;
	int  *result_3;
	char *checkwinner_1_arg;
	
	int player = 0;                              /* Player number - 0 or 1               */
	int go = 0;                                  /* Square selection number for turn     */
	int row = 0;                                 /* Row index for a square               */  
	int column = 0;                              /* Column index for a square            */
	//int winner = -1;                              /* The winning player                   */

#ifndef	DEBUG
	clnt = clnt_create (host, TTT, V1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
do{
	do{
	//PLAY	
	result_1 = currentboard_1((void*)&currentboard_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("%s\n",result_1);
	
	
	printf("\nPlayer %d, please enter the number of the square "
	     "where you want to place your %c (or 0 to refresh the board): ", player,(player==1)?'X':'O');
    scanf(" %d", &go);

   if (go == 0){
	result_2 = 0;
	continue;
    }

      row = --go/3;                                 /* Get row index of square      */
      column = go%3;                                /* Get column index of square   */
	
	//play_1_arg =malloc(sizeof (play_args));
	play_1_arg.row=row;
	play_1_arg.column=column;
	play_1_arg.player=player;
	
	result_2 = play_1(&play_1_arg, clnt);
	//if (result_2 == (int *) NULL) {
	//	clnt_perror (clnt, "call failed");
	//}
	
	
}while(result_2!=0);
	//RESULT CHECK

	result_3 = checkwinner_1((void*)&checkwinner_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
}while(*result_3 == -1);
	//POST GAME
	
	result_1 = currentboard_1((void*)&currentboard_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("%s\n",result_1);

	if(*result_3 == 2)
		printf("\nHow boring, it is a draw\n");
	else
		printf("\nCongratulations, player %d, YOU ARE THE WINNER!\n", result_3);


#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	ttt_1 (host);
exit (0);
}
